version: "3"

services:
  frontend:
    build:
      context: ../src/frontend
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ../src/frontend/docker/nginx.conf:/etc/nginx/nginx.conf:ro

  backend:
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    build:
      context: ../src/backend
      dockerfile: docker/Dockerfile
    ports: # Used only locally
      - "8080:8080"
    volumes:
      - ../src/backend/data:/app/data
